### ISSUE TITLE
DECISION: currency or chips?

### ISSUE THREAD

**Issue by spencerk80** [spencerk80/CasinoSuite#4]
We never really thought of it. So if we want to make the change, NOW is the time. Otherwise there'll be a lot more code to handle. Also, while on topic, how high of stakes are we playing? Each game costs like $5, $10, $20, etc?

**Comment by spencerk80** [comment]
So, without any responded or input, must I alone make the call?

**Comment by spencerk80** [comment]
Response *

**Comment by OregonFanBoy** [comment]
I think using chips is a good way to go since most of the games are considered floor games.
I propose two ideas.

#1) In the main menu ask the player how much money they wish to use to gamble with, and that will be the total amount of dollars the player walks into the casino with. In a real casino, you can walk up to the table and throw down dollar bills and the game teller will convert the dollars into chips. So I suggest that when the player chooses the game such as Yahtzee, ask the player how much cash they would like to play with and convert that into casino chips. Now the player will have two forms of currency, chips and dollars. Now use the chips to gamble with. We'll want to have different denominations of chips for the purpose of how much they want to bet per hand/play. Slot machine should only take dollars, but only up to $100 at a time because I have never seen a slot machine take chips, so we will want to be able to convert chips back to dollars in case the player wants to go from a floor game to a slot machine.

#2) Continue the use of idea #1 and add in a bank function, where the player can go to and manually convert chips to dollars

**Comment by spencerk80** [comment]
I like two better. I'd rather have one place where code has to perform the job.

**Comment by spencerk80** [comment]
At this time, I'm voting against chips. If we want to change it up, we can always make a versions 2. Vote is open, if both of you vote for it, it shall be done. But since Noctis won't look at the website and discussion......I don't know how we'll tie break without his input.

**Comment by OregonFanBoy** [comment]
Since I'm working with dollars only for slot machine. I'm okay with using only dollars. To save time on writing another class for conversion of money to chips, I vote just to keep using dollars. Perhaps at a later point in time, we could implement using chips.

**Comment by spencerk80** [comment]
Vote stands as majority for money. We keep money and this discussion is closed now.
